### ISSUE TITLE
Fail to build with GCC 14

### ISSUE THREAD

**Issue by eribertomota** [eribertomota/sniffit#7]
When building Sniffit over GCC 14, we can see:

```
gcc -DHAVE_CONFIG_H -I. -I..  -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DHAVE_LIBNCURSES=1 -DHAVE_SHMGET=1 -DHAVE_ATEXIT=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DSIZEOF_UNSIGNED_SHORT_INT=2 -DSIZEOF_UNSIGNED_LONG_INT=8 -DSIZEOF_UNSIGNED_INT=4 -DUSE_32_INT=1 -DLINUX=1  -lncurses -lpcap -g -O2 -MT sn_packets.o -MD -MP -MF .deps/sn_packets.Tpo -c -o sn_packets.o sn_packets.c
sn_packets.c: In function ‘unwrap_packet’:
sn_packets.c:68:32: error: passing argument 1 of ‘in_cksum’ from incompatible pointer type [-Wincompatible-pointer-types]
   68 |                 if(in_cksum((sp+PROTO_HEAD),unwrapped->IP_len) != IPhead.checksum)
      |                             ~~~^~~~~~~~~~~~
      |                                |
      |                                unsigned char *
sn_packets.c:14:41: note: expected ‘short unsigned int *’ but argument is of type ‘unsigned char *’
   14 | unsigned short in_cksum(unsigned short *addr,int len)
      |                         ~~~~~~~~~~~~~~~~^~~~
make[2]: *** [Makefile:380: sn_packets.o] Error 1
make[2]: Leaving directory '/PKGS/sniffit/sniffit-0.6/src'
make[1]: *** [Makefile:488: all-recursive] Error 1
make[1]: Leaving directory '/PKGS/sniffit/sniffit-0.6'
make: *** [Makefile:343: all] Error 2
```

On Debian, with -Werror turned on, the result is:

```
gcc -DHAVE_CONFIG_H -I. -I..  -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DHAVE_LIBNCURSES=1 -DHAVE_SHMGET=1 -DHAVE_ATEXIT=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DSIZEOF_UNSIGNED_SHORT_INT=2 -DSIZEOF_UNSIGNED_LONG_INT=8 -DSIZEOF_UNSIGNED_INT=4 -DUSE_32_INT=1 -DLINUX=1 -Wdate-time -D_FORTIFY_SOURCE=2 -lncurses -lpcap -g -O2 -Werror=implicit-function-declaration -ffile-prefix-map=/PKGS/sniffit/sniffit-0.6=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -c -o sniffit.o sniffit.c
sn_logfile.c: In function ‘open_logfile’:
sn_logfile.c:96:8: error: passing argument 1 of ‘fchmod’ makes integer from pointer without a cast [-Wint-conversion]
   96 | fchmod(LogFILE,  S_IWUSR|S_IRUSR);
      |        ^~~~~~~
      |        |
      |        FILE *
In file included from sn_logfile.c:9:
/usr/include/x86_64-linux-gnu/sys/stat.h:365:24: note: expected ‘int’ but argument is of type ‘FILE *’
  365 | extern int fchmod (int __fd, __mode_t __mode) __THROW;
      |                    ~~~~^~~~
sn_packets.c: In function ‘unwrap_packet’:
sn_packets.c:68:32: error: passing argument 1 of ‘in_cksum’ from incompatible pointer type [-Wincompatible-pointer-types]
   68 |                 if(in_cksum((sp+PROTO_HEAD),unwrapped->IP_len) != IPhead.checksum)
      |                             ~~~^~~~~~~~~~~~
      |                                |
      |                                unsigned char *
sn_packets.c:14:41: note: expected ‘short unsigned int *’ but argument is of type ‘unsigned char *’
   14 | unsigned short in_cksum(unsigned short *addr,int len)
      |                         ~~~~~~~~~~~~~~~~^~~~
make[3]: *** [Makefile:384: sn_logfile.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [Makefile:384: sn_packets.o] Error 1
sn_cfgfile.c: In function ‘read_cfg_file’:
sn_cfgfile.c:464:9: warning: ignoring return value of ‘fgets’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  464 |         fgets(lineptr,259,cfgfile);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~
sn_interface.c: In function ‘mask_status’:
sn_interface.c:196:3: error: assignment to ‘unsigned char *’ from incompatible pointer type ‘_32_bit *’ {aka ‘unsigned int *’} [-Wincompatible-pointer-types]
  196 | ad=&(mask->source_ip);
      |   ^
sn_interface.c:202:3: error: assignment to ‘unsigned char *’ from incompatible pointer type ‘_32_bit *’ {aka ‘unsigned int *’} [-Wincompatible-pointer-types]
  202 | ad=&(mask->destination_ip);
      |   ^
sn_interface.c: In function ‘packet_info_handler’:
sn_interface.c:492:63: warning: ' ' flag used with ‘%u’ gnu_printf format [-Wformat=]
  492 | mvwprintw(packets_box.work_window,0,1,"IP packets/sec.  : % 12u",(*IP_nr_of_packets)/INFO_TIMER);
      |                                                               ^
In file included from sn_plugins.h:23,
                 from sniffit.c:36:
dns_plugin.plug: In function ‘PL_DNS_plugin’:
sn_interface.c:493:63: warning: ' ' flag used with ‘%u’ gnu_printf format [-Wformat=]
  493 | mvwprintw(packets_box.work_window,1,1,"TCP packets/sec. : % 12u",(*TCP_nr_of_packets)/INFO_TIMER);
      |                                                               ^
dns_plugin.plug:87:12: error: assignment to ‘struct PL_DNS_header *’ from incompatible pointer type ‘struct DNS_header *’ [-Wincompatible-pointer-types]
   87 | dns_dnshead= (struct DNS_header *) (dns_buffer+udp_start+sizeof(struct UDP_header));
      |            ^
sn_interface.c:494:63: warning: ' ' flag used with ‘%u’ gnu_printf format [-Wformat=]
  494 | mvwprintw(packets_box.work_window,2,1,"ICMP packets/sec.: % 12u",(*ICMP_nr_of_packets)/INFO_TIMER);
      |                                                               ^
sn_interface.c:495:63: warning: ' ' flag used with ‘%u’ gnu_printf format [-Wformat=]
  495 | mvwprintw(packets_box.work_window,3,1,"UDP packets/sec. : % 12u",(*UDP_nr_of_packets)/INFO_TIMER);
      |                                                               ^
sniffit.c: In function ‘packethandler’:
sniffit.c:1108:43: error: passing argument 2 of ‘pcap_dump’ from incompatible pointer type [-Wincompatible-pointer-types]
 1108 |     pcap_dump((unsigned char *) dev_dump, p_header, sp);
      |                                           ^~~~~~~~
      |                                           |
      |                                           const struct packetheader *
In file included from /usr/include/pcap.h:43,
                 from sniffit.c:25:
/usr/include/pcap/pcap.h:792:37: note: expected ‘const struct pcap_pkthdr *’ but argument is of type ‘const struct packetheader *’
  792 | PCAP_API void   pcap_dump(u_char *, const struct pcap_pkthdr *, const u_char *);
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
sniffit.c:1109:12: error: returning ‘int’ from a function with return type ‘pcap_handler’ {aka ‘void (*)(unsigned char *, const struct pcap_pkthdr *, const unsigned char *)’} makes pointer from integer without a cast [-Wint-conversion]
 1109 |     return 1;
      |            ^
sniffit.c:1155:32: warning: format ‘%lX’ expects argument of type ‘long unsigned int’, but argument 2 has type ‘__uint32_t’ {aka ‘unsigned int’} [-Wformat=]
 1155 |       printf ("   SEQ (hex): %lX   ", ntohl (tcphead.seq_nr));
      |                              ~~^
      |                                |
      |                                long unsigned int
      |                              %X
sniffit.c:1157:31: warning: format ‘%lX’ expects argument of type ‘long unsigned int’, but argument 2 has type ‘__uint32_t’ {aka ‘unsigned int’} [-Wformat=]
 1157 |         printf ("ACK (hex): %lX\n", ntohl (tcphead.ACK_nr));
      |                             ~~^
      |                               |
      |                               long unsigned int
      |                             %X
sniffit.c:1190:24: error: returning ‘int’ from a function with return type ‘pcap_handler’ {aka ‘void (*)(unsigned char *, const struct pcap_pkthdr *, const unsigned char *)’} makes pointer from integer without a cast [-Wint-conversion]
 1190 |                 return 1;
      |                        ^
sniffit.c:1194:24: error: returning ‘int’ from a function with return type ‘pcap_handler’ {aka ‘void (*)(unsigned char *, const struct pcap_pkthdr *, const unsigned char *)’} makes pointer from integer without a cast [-Wint-conversion]
 1194 |                 return 1;
      |                        ^
sniffit.c:1260:14: error: returning ‘int’ from a function with return type ‘pcap_handler’ {aka ‘void (*)(unsigned char *, const struct pcap_pkthdr *, const unsigned char *)’} makes pointer from integer without a cast [-Wint-conversion]
 1260 |       return 1;
      |              ^
In file included from sniffit.c:1271:
sn_analyse.c:13:16: error: returning ‘int’ from a function with return type ‘pcap_handler’ {aka ‘void (*)(unsigned char *, const struct pcap_pkthdr *, const unsigned char *)’} makes pointer from integer without a cast [-Wint-conversion]
   13 |         return 1;
      |                ^
sn_analyse.c:29:10: error: returning ‘int’ from a function with return type ‘pcap_handler’ {aka ‘void (*)(unsigned char *, const struct pcap_pkthdr *, const unsigned char *)’} makes pointer from integer without a cast [-Wint-conversion]
   29 |   return 1;
      |          ^
sn_analyse.c:43:37: error: returning ‘int’ from a function with return type ‘pcap_handler’ {aka ‘void (*)(unsigned char *, const struct pcap_pkthdr *, const unsigned char *)’} makes pointer from integer without a cast [-Wint-conversion]
   43 | if((dummy&FIN)||(dummy&RST)) return 1; /* needed, cauz entry don't exist  */
      |                                     ^
sn_analyse.c:53:51: warning: passing argument 3 of ‘sbuf_update’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   53 |   sbuf_update(dummy_pointer,ntohl(tcphead.seq_nr),data,info.DATA_len);
      |                                                   ^~~~
sniffit.c:414:20: note: expected ‘char *’ but argument is of type ‘const unsigned char *’
  414 |              char *data, int len)
      |              ~~~~~~^~~~
sn_analyse.c:83:52: warning: passing argument 3 of ‘record_buf’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   83 |     record_buf(dummy_pointer,ntohl(tcphead.seq_nr),data,info.DATA_len,0);
      |                                                    ^~~~
sniffit.c:359:19: note: expected ‘char *’ but argument is of type ‘const unsigned char *’
  359 |             char *data, int len, int type)
      |             ~~~~~~^~~~
sn_analyse.c:95:54: warning: passing argument 3 of ‘record_buf’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   95 |       record_buf(dummy_pointer,ntohl(tcphead.seq_nr),data,info.DATA_len,0);
      |                                                      ^~~~
sniffit.c:359:19: note: expected ‘char *’ but argument is of type ‘const unsigned char *’
  359 |             char *data, int len, int type)
      |             ~~~~~~^~~~
sn_analyse.c:117:51: warning: passing argument 3 of ‘sbuf_update’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  117 |   sbuf_update(dummy_pointer,ntohl(tcphead.seq_nr),data,info.DATA_len);
      |                                                   ^~~~
sniffit.c:414:20: note: expected ‘char *’ but argument is of type ‘const unsigned char *’
  414 |              char *data, int len)
      |              ~~~~~~^~~~
make[3]: *** [Makefile:384: sn_interface.o] Error 1
sn_analyse.c:200:8: error: returning ‘int’ from a function with return type ‘pcap_handler’ {aka ‘void (*)(unsigned char *, const struct pcap_pkthdr *, const unsigned char *)’} makes pointer from integer without a cast [-Wint-conversion]
  200 | return 1;
      |        ^
sn_analyse.c:201:8: error: returning ‘int’ from a function with return type ‘pcap_handler’ {aka ‘void (*)(unsigned char *, const struct pcap_pkthdr *, const unsigned char *)’} makes pointer from integer without a cast [-Wint-conversion]
  201 | return 1;  /* DON'T FORGET THEM!!!! */
      |        ^
sniffit.c:1340:14: error: returning ‘int’ from a function with return type ‘pcap_handler’ {aka ‘void (*)(unsigned char *, const struct pcap_pkthdr *, const unsigned char *)’} makes pointer from integer without a cast [-Wint-conversion]
 1340 |       return 1;
      |              ^
sniffit.c:1373:14: error: returning ‘int’ from a function with return type ‘pcap_handler’ {aka ‘void (*)(unsigned char *, const struct pcap_pkthdr *, const unsigned char *)’} makes pointer from integer without a cast [-Wint-conversion]
 1373 |       return 1;
      |              ^
sniffit.c: In function ‘main’:
sniffit.c:1523:20: error: passing argument 2 of ‘signal’ from incompatible pointer type [-Wincompatible-pointer-types]
 1523 |   signal (SIGINT,  my_exit);    /* graceful termination in different ways */
      |                    ^~~~~~~
      |                    |
      |                    void (*)(void)
In file included from sniffit.c:8:
/usr/include/signal.h:88:57: note: expected ‘__sighandler_t’ {aka ‘void (*)(int)’} but argument is of type ‘void (*)(void)’
   88 | extern __sighandler_t signal (int __sig, __sighandler_t __handler)
      |                                          ~~~~~~~~~~~~~~~^~~~~~~~~
sniffit.c:1524:20: error: passing argument 2 of ‘signal’ from incompatible pointer type [-Wincompatible-pointer-types]
 1524 |   signal (SIGHUP,  my_exit);
      |                    ^~~~~~~
      |                    |
      |                    void (*)(void)
/usr/include/signal.h:88:57: note: expected ‘__sighandler_t’ {aka ‘void (*)(int)’} but argument is of type ‘void (*)(void)’
   88 | extern __sighandler_t signal (int __sig, __sighandler_t __handler)
      |                                          ~~~~~~~~~~~~~~~^~~~~~~~~
sniffit.c:1525:20: error: passing argument 2 of ‘signal’ from incompatible pointer type [-Wincompatible-pointer-types]
 1525 |   signal (SIGTERM, my_exit);
      |                    ^~~~~~~
      |                    |
      |                    void (*)(void)
/usr/include/signal.h:88:57: note: expected ‘__sighandler_t’ {aka ‘void (*)(int)’} but argument is of type ‘void (*)(void)’
   88 | extern __sighandler_t signal (int __sig, __sighandler_t __handler)
      |                                          ~~~~~~~~~~~~~~~^~~~~~~~~
sniffit.c:1564:43: warning: macro "__DATE__" might prevent reproducible builds [-Wdate-time]
 1564 |           printf ("Binary build %s %s\n", __DATE__, __TIME__);
      |                                           ^~~~~~~~
sniffit.c:1564:53: warning: macro "__TIME__" might prevent reproducible builds [-Wdate-time]
 1564 |           printf ("Binary build %s %s\n", __DATE__, __TIME__);
      |                                                     ^~~~~~~~
sniffit.c:1774:5: warning: ‘pcap_lookupdev’ is deprecated: use 'pcap_findalldevs' and use the first device [-Wdeprecated-declarations]
 1774 |     if((dev = pcap_lookupdev (ebuf)) == NULL)
      |     ^~
/usr/include/pcap/pcap.h:444:18: note: declared here
  444 | PCAP_API char   *pcap_lookupdev(char *);
      |                  ^~~~~~~~~~~~~~
sniffit.c:1801:20: warning: extra tokens at end of #ifdef directive
 1801 | #ifdef PLUGIN0_INIT()
      |                    ^
sniffit.c:1805:20: warning: extra tokens at end of #ifdef directive
 1805 | #ifdef PLUGIN1_INIT()
      |                    ^
sniffit.c:1809:20: warning: extra tokens at end of #ifdef directive
 1809 | #ifdef PLUGIN2_INIT()
      |                    ^
sniffit.c:1813:20: warning: extra tokens at end of #ifdef directive
 1813 | #ifdef PLUGIN3_INIT()
      |                    ^
sniffit.c:1817:20: warning: extra tokens at end of #ifdef directive
 1817 | #ifdef PLUGIN4_INIT()
      |                    ^
sniffit.c:1821:20: warning: extra tokens at end of #ifdef directive
 1821 | #ifdef PLUGIN5_INIT()
      |                    ^
sniffit.c:1825:20: warning: extra tokens at end of #ifdef directive
 1825 | #ifdef PLUGIN6_INIT()
      |                    ^
sniffit.c:1829:20: warning: extra tokens at end of #ifdef directive
 1829 | #ifdef PLUGIN7_INIT()
      |                    ^
sniffit.c:1833:20: warning: extra tokens at end of #ifdef directive
 1833 | #ifdef PLUGIN8_INIT()
      |                    ^
sniffit.c:1837:20: warning: extra tokens at end of #ifdef directive
 1837 | #ifdef PLUGIN9_INIT()
      |                    ^
sniffit.c:1865:24: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
 1865 |       printf ("Shared %d\n", memsize);
      |                       ~^     ~~~~~~~
      |                        |     |
      |                        int   long unsigned int
      |                       %ld
sniffit.c:1868:18: error: assignment to ‘int *’ from incompatible pointer type ‘char *’ [-Wincompatible-pointer-types]
 1868 |       DATAlength = timing + sizeof (int);
      |                  ^
sniffit.c:1869:23: error: assignment to ‘char *’ from incompatible pointer type ‘int *’ [-Wincompatible-pointer-types]
 1869 |       connection_data = DATAlength + sizeof (int);
      |                       ^
sniffit.c:1870:18: error: assignment to ‘int *’ from incompatible pointer type ‘char *’ [-Wincompatible-pointer-types]
 1870 |       LISTlength = connection_data + LENGTH_OF_INTERPROC_DATA;
      |                  ^
sniffit.c:1871:12: error: assignment to ‘struct snif_mask *’ from incompatible pointer type ‘int *’ [-Wincompatible-pointer-types]
 1871 |       mask = LISTlength + sizeof (int);
      |            ^
sniffit.c:1872:26: error: assignment to ‘char *’ from incompatible pointer type ‘struct snif_mask *’ [-Wincompatible-pointer-types]
 1872 |       logged_connections = mask + sizeof (struct snif_mask);
      |                          ^
sniffit.c:1875:25: error: assignment to ‘unsigned int *’ from incompatible pointer type ‘char *’ [-Wincompatible-pointer-types]
 1875 |       TCP_nr_of_packets = running_connections + (sizeof (struct shared_conn_data) * CONNECTION_CAPACITY);
      |                         ^
sniffit.c:1876:28: error: assignment to ‘long unsigned int *’ from incompatible pointer type ‘unsigned int *’ [-Wincompatible-pointer-types]
 1876 |       TCP_bytes_in_packets = TCP_nr_of_packets + sizeof (int);
      |                            ^
sniffit.c:1877:26: error: assignment to ‘unsigned int *’ from incompatible pointer type ‘long unsigned int *’ [-Wincompatible-pointer-types]
 1877 |       ICMP_nr_of_packets = TCP_bytes_in_packets + sizeof (unsigned long);
      |                          ^
sniffit.c:1879:28: error: assignment to ‘long unsigned int *’ from incompatible pointer type ‘unsigned int *’ [-Wincompatible-pointer-types]
 1879 |       UDP_bytes_in_packets = UDP_nr_of_packets + sizeof (int);
      |                            ^
sniffit.c:1880:24: error: assignment to ‘unsigned int *’ from incompatible pointer type ‘long unsigned int *’ [-Wincompatible-pointer-types]
 1880 |       IP_nr_of_packets = UDP_bytes_in_packets + sizeof (unsigned long);
      |                        ^
sniffit.c:1895:32: error: passing argument 3 of ‘pcap_loop’ from incompatible pointer type [-Wincompatible-pointer-types]
 1895 |                                interactive_packethandler, NULL) < 0)
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                |
      |                                void (* (*)(char *, const struct packetheader *, const unsigned char *))(u_char *, const struct pcap_pkthdr *, const u_char *) {aka void (* (*)(char *, const struct packetheader *, const unsigned char *))(unsigned char *, const struct pcap_pkthdr *, const unsigned char *)}
/usr/include/pcap/pcap.h:614:42: note: expected ‘pcap_handler’ {aka ‘void (*)(unsigned char *, const struct pcap_pkthdr *, const unsigned char *)’} but argument is of type ‘void (* (*)(char *, const struct packetheader *, const unsigned char *))(u_char *, const struct pcap_pkthdr *, const u_char *)’ {aka ‘void (* (*)(char *, const struct packetheader *, const unsigned char *))(unsigned char *, const struct pcap_pkthdr *, const unsigned char *)’}
  614 | PCAP_API int    pcap_loop(pcap_t *, int, pcap_handler, u_char *);
      |                                          ^~~~~~~~~~~~
sniffit.c:1928:41: error: passing argument 3 of ‘pcap_loop’ from incompatible pointer type [-Wincompatible-pointer-types]
 1928 |       switch (pcap_loop (dev_desc, CNT, packethandler, (unsigned char *) &ipaddr))
      |                                         ^~~~~~~~~~~~~
      |                                         |
      |                                         void (* (*)(unsigned char *, const struct packetheader *, const unsigned char *))(u_char *, const struct pcap_pkthdr *, const u_char *) {aka void (* (*)(unsigned char *, const struct packetheader *, const unsigned char *))(unsigned char *, const struct pcap_pkthdr *, const unsigned char *)}
/usr/include/pcap/pcap.h:614:42: note: expected ‘pcap_handler’ {aka ‘void (*)(unsigned char *, const struct pcap_pkthdr *, const unsigned char *)’} but argument is of type ‘void (* (*)(unsigned char *, const struct packetheader *, const unsigned char *))(u_char *, const struct pcap_pkthdr *, const u_char *)’ {aka ‘void (* (*)(unsigned char *, const struct packetheader *, const unsigned char *))(unsigned char *, const struct pcap_pkthdr *, const unsigned char *)’}
  614 | PCAP_API int    pcap_loop(pcap_t *, int, pcap_handler, u_char *);
      |                                          ^~~~~~~~~~~~
make[3]: *** [Makefile:384: sniffit.o] Error 1
make[3]: Leaving directory '/PKGS/sniffit/sniffit-0.6/src'
make[2]: *** [Makefile:488: all-recursive] Error 1
make[2]: Leaving directory '/PKGS/sniffit/sniffit-0.6'
make[1]: *** [Makefile:343: all] Error 2
make[1]: Leaving directory '/PKGS/sniffit/sniffit-0.6'
dh_auto_build: error: make -j16 returned exit code 2
make: *** [debian/rules:7: binary] Error 25
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
debuild: fatal error at line 1184:
dpkg-buildpackage -us -uc -ui failed
```

**Comment by infrastation** [comment]
Many of those warnings have already been fixed in the master branch. The 10 warnings in the block just after `timing = SHARED` all have the same root cause and indeed mean a problem on architectures that do not allow unaligned access. I tried to produce a nice solution to that, but eventually concluded a nice solution may be not possible. That said, with quite a bit of additional `memcpy()` calls it may be possible to have a solution that is not nice, but is safe. Didn't look into the `in_cksum()` warning yet.

**Comment by infrastation** [comment]
In other words, to get a warning-free build on Debian 12 with GCC 12.2 it would take to solve three different remaining problems. Could be a couple more with Clang.

**Comment by eribertomota** [comment]
Hi @infrastation,

Thanks a lot for your reply. Sorry, sorry, sorry, I forgot about the recent commits on master. The main problem to solve is make sniffit build with GCC 14 on Debian Sid. I will test your commits. Warnings aren't a problem.

**Comment by eribertomota** [comment]
This is the result with current master:

```
gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2  -g -O2 -Werror=implicit-function-declaration -ffile-prefix-map=/PKGS/sniffit2/sniffit=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -c -o sniffit.o sniffit.c
sn_packets.c: In function ‘unwrap_packet’:
sn_packets.c:68:32: error: passing argument 1 of ‘in_cksum’ from incompatible pointer type [-Wincompatible-pointer-types]
   68 |                 if(in_cksum((sp+PROTO_HEAD),unwrapped->IP_len) != IPhead.checksum)
      |                             ~~~^~~~~~~~~~~~
      |                                |
      |                                unsigned char *
sn_packets.c:14:41: note: expected ‘short unsigned int *’ but argument is of type ‘unsigned char *’
   14 | unsigned short in_cksum(unsigned short *addr,int len)
      |                         ~~~~~~~~~~~~~~~~^~~~
make[3]: *** [Makefile:367: sn_packets.o] Error 1
make[3]: *** Waiting for unfinished jobs....
sn_cfgfile.c: In function ‘read_cfg_file’:
sn_cfgfile.c:464:9: warning: ignoring return value of ‘fgets’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  464 |         fgets(lineptr,259,cfgfile);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~
sn_interface.c: In function ‘mask_status’:
sn_interface.c:201:3: error: assignment to ‘unsigned char *’ from incompatible pointer type ‘_32_bit *’ {aka ‘unsigned int *’} [-Wincompatible-pointer-types]
  201 | ad=&(mask->source_ip);
      |   ^
sn_interface.c:207:3: error: assignment to ‘unsigned char *’ from incompatible pointer type ‘_32_bit *’ {aka ‘unsigned int *’} [-Wincompatible-pointer-types]
  207 | ad=&(mask->destination_ip);
      |   ^
sniffit.c: In function ‘main’:
sniffit.c:1567:43: warning: macro "__DATE__" might prevent reproducible builds [-Wdate-time]
 1567 |           printf ("Binary build %s %s\n", __DATE__, __TIME__);
      |                                           ^~~~~~~~
sniffit.c:1567:53: warning: macro "__TIME__" might prevent reproducible builds [-Wdate-time]
 1567 |           printf ("Binary build %s %s\n", __DATE__, __TIME__);
      |                                                     ^~~~~~~~
sniffit.c:1879:18: error: assignment to ‘int *’ from incompatible pointer type ‘char *’ [-Wincompatible-pointer-types]
 1879 |       DATAlength = timing + sizeof (int);
      |                  ^
sniffit.c:1880:23: error: assignment to ‘char *’ from incompatible pointer type ‘int *’ [-Wincompatible-pointer-types]
 1880 |       connection_data = DATAlength + sizeof (int);
      |                       ^
sniffit.c:1881:18: error: assignment to ‘int *’ from incompatible pointer type ‘char *’ [-Wincompatible-pointer-types]
 1881 |       LISTlength = connection_data + LENGTH_OF_INTERPROC_DATA;
      |                  ^
sniffit.c:1882:12: error: assignment to ‘struct snif_mask *’ from incompatible pointer type ‘int *’ [-Wincompatible-pointer-types]
 1882 |       mask = LISTlength + sizeof (int);
      |            ^
sniffit.c:1883:26: error: assignment to ‘char *’ from incompatible pointer type ‘struct snif_mask *’ [-Wincompatible-pointer-types]
 1883 |       logged_connections = mask + sizeof (struct snif_mask);
      |                          ^
sniffit.c:1886:25: error: assignment to ‘unsigned int *’ from incompatible pointer type ‘char *’ [-Wincompatible-pointer-types]
 1886 |       TCP_nr_of_packets = running_connections + (sizeof (struct shared_conn_data) * CONNECTION_CAPACITY);
      |                         ^
sniffit.c:1887:28: error: assignment to ‘long unsigned int *’ from incompatible pointer type ‘unsigned int *’ [-Wincompatible-pointer-types]
 1887 |       TCP_bytes_in_packets = TCP_nr_of_packets + sizeof (int);
      |                            ^
sniffit.c:1888:26: error: assignment to ‘unsigned int *’ from incompatible pointer type ‘long unsigned int *’ [-Wincompatible-pointer-types]
 1888 |       ICMP_nr_of_packets = TCP_bytes_in_packets + sizeof (unsigned long);
      |                          ^
sniffit.c:1890:28: error: assignment to ‘long unsigned int *’ from incompatible pointer type ‘unsigned int *’ [-Wincompatible-pointer-types]
 1890 |       UDP_bytes_in_packets = UDP_nr_of_packets + sizeof (int);
      |                            ^
sniffit.c:1891:24: error: assignment to ‘unsigned int *’ from incompatible pointer type ‘long unsigned int *’ [-Wincompatible-pointer-types]
 1891 |       IP_nr_of_packets = UDP_bytes_in_packets + sizeof (unsigned long);
      |                        ^
make[3]: *** [Makefile:367: sn_interface.o] Error 1
make[3]: *** [Makefile:367: sniffit.o] Error 1
```

**Comment by infrastation** [comment]
Fixed the two warnings in `sn_interface.c` to make this problem smaller.

**Comment by infrastation** [comment]
Made `in_cksum()` warning-free as well. The warnings in `sniffit.c` would require a bit more substantial work, not doing it right away.

**Comment by eribertomota** [comment]
> Fixed the two warnings in `sn_interface.c` to make this problem smaller.

Great!

**Comment by eribertomota** [comment]
> Made `in_cksum()` warning-free as well. The warnings in `sniffit.c` would require a bit more substantial work, not doing it right away.

Thanks a lot for your work.

Because of the build errors, maybe sniffit don't be released in Debian 13 Trixie. This is not a big problem, however, if you are interested to fix Sniffit for Trixie, I have up to April 02 to upload a new version with changes. Debian will freeze to release a new version soon. A release point occurs every 2 years. But I repeat: you are a volunteer and it is not a problem if Sniffit was not released in Debian 13. Thanks again.

**Comment by infrastation** [comment]
You are welcome. The master branch now includes a few more minor improvements, but the compiler warnings remain. I spent some time studying the root cause in detail and found that the warnings are not just cosmetic, there are various bugs that require a substantial amount of work to fix. It is going to take time.

**Comment by eribertomota** [comment]
Hi @infrastation,

Thanks again for your time and work. The source code remains not building with GCC 14.

Take your time. I will wait for a solution when as possible.

Cheers,

Eriberto
